import { Router, type IRouter } from "express";
import healthRouter from "./health";
import dashboardRouter from "./dashboard";
import accountsRouter from "./accounts";
import projectsRouter from "./projects";
import phasesRouter from "./phases";
import tasksRouter from "./tasks";
import usersRouter from "./users";
import timeEntriesRouter from "./timeEntries";
import timesheetsRouter from "./timesheets";
import invoicesRouter from "./invoices";
import invoiceLineItemsRouter from "./invoiceLineItems";
import rateCardsRouter from "./rateCards";
import allocationsRouter from "./allocations";
import reportsRouter from "./reports";
import notificationsRouter from "./notifications";
import resourceRequestsRouter from "./resourceRequests";
import projectTemplatesRouter from "./projectTemplates";
import csatRouter from "./csat";
import billingSchedulesRouter from "./billingSchedules";
import revenueEntriesRouter from "./revenueEntries";
import timeOffRouter from "./timeOff";
import skillsRouter from "./skills";
import taskDetailsRouter from "./taskDetails";
import adminSettingsRouter from "./adminSettings";
import customFieldsRouter from "./customFields";
import auditLogRouter from "./auditLog";
import documentsRouter from "./documents";
import formsRouter from "./forms";
import prospectsRouter from "./prospects";
import opportunitiesRouter from "./opportunities";
import portalRouter from "./portal";
import changeOrdersRouter from "./changeOrders";
import taskDependenciesRouter from "./taskDependencies";
import baselinesRouter from "./baselines";

const router: IRouter = Router();

router.use(healthRouter);
router.use(dashboardRouter);
router.use(accountsRouter);
router.use(projectsRouter);
router.use(phasesRouter);
router.use(tasksRouter);
router.use(usersRouter);
router.use(timeEntriesRouter);
router.use(timesheetsRouter);
router.use(invoiceLineItemsRouter);
router.use(invoicesRouter);
router.use(rateCardsRouter);
router.use(allocationsRouter);
router.use(reportsRouter);
router.use(notificationsRouter);
router.use(resourceRequestsRouter);
router.use(projectTemplatesRouter);
router.use(csatRouter);
router.use(billingSchedulesRouter);
router.use(revenueEntriesRouter);
router.use(timeOffRouter);
router.use(skillsRouter);
router.use(taskDetailsRouter);
router.use(adminSettingsRouter);
router.use(customFieldsRouter);
router.use(auditLogRouter);
router.use(documentsRouter);
router.use(formsRouter);
router.use(prospectsRouter);
router.use(opportunitiesRouter);
router.use(portalRouter);
router.use(changeOrdersRouter);
router.use(taskDependenciesRouter);
router.use(baselinesRouter);

export default router;
